# Generated by Django 5.0.2 on 2024-02-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orders_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_title', models.CharField(choices=[('LU', 'login'), ('UR', 'user'), ('SL', 'saler'), ('AM', 'admin')], max_length=10)),
            ],
        ),
    ]
