# Generated by Django 5.0.2 on 2024-02-21 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_title_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Права', 'verbose_name_plural': 'Права'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.IntegerField(unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name_of_title',
            field=models.CharField(choices=[('LU', 'login'), ('UR', 'user'), ('SL', 'saler'), ('AM', 'admin')], max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='title',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
